### ISSUE TITLE
Division by zero in MEs for  several processes

### ISSUE THREAD

**Issue by andriish** [LucianHL/SuperChic#69]
Division by zero in MEs for  several processes.

The way to understand/reproduce:

1) Compile w/o the FPE flags and run init
2) Compile with FPE flags and run the process, e.g. in the test
```
ctest --test-dir BUILD -j 10 -R SUPERCHIC_LHC13ppunw_LHC13ppunw_3_el_lhe --output-on-failure
```
The result is 
```
Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#0  0x7f81c8823a12 in ???
#1  0x7f81c8822ba5 in ???
#2  0x7f81c843e9ff in ???
	at /usr/src/debug/glibc-2.35-22.fc36.x86_64/signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#3  0x7f81c8c50d43 in gg_
	at /home/andriish/Projects/SuperChic/src/subamps/ggjets.f:12
#4  0x7f81c8c2429f in wtgen_
	at /home/andriish/Projects/SuperChic/src/main/wtgen.f:23
#5  0x7f81c8c17cb8 in cs_
	at /home/andriish/Projects/SuperChic/src/main/main.f:748
#6  0x7f81c8c2b204 in master.0.vegas
	at /home/andriish/Projects/SuperChic/src/int/vegas.f:121
#7  0x409103 in superchic
	at /home/andriish/Projects/SuperChic/src/main/superchic.f:836
#8  0x4044b7 in main
	at /home/andriish/Projects/SuperChic/src/main/superchic.f:946


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   6.99 sec

The following tests FAILED:
	 12 - SUPERCHIC_LHC13ppunw_LHC13ppunw_3_el_lhe (Failed)

```

The reason is this code:
```
      cphi=p1(1)/dsqrt(p1(1)**2+p1(2)**2)
      sphi=p1(2)/dsqrt(p1(1)**2+p1(2)**2)
 ```
for the case when p1(1)=0 and p1(2)=0.
However, fixing this code does not help, as there are other cases of division by zero in the same code (ggjets.f ).

The other processes, which are, probably affected:
3,4,7,8,14,15,16,54,55,61,71,72,82

Best regards,

Andrii

**Comment by andriish** [comment]
Solved. One nees cuts for most of the processes.
